# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldata',
            name='diskuse',
            field=models.IntegerField(default=0, verbose_name='硬盘使用量'),
        ),
        migrations.AddField(
            model_name='alldata',
            name='memoryuse',
            field=models.IntegerField(default=0, verbose_name='内存使用量'),
        ),
    ]
