# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipdata', '0002_auto_20191120_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipinfo',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'service'), (1, 'big_data')], default=0, verbose_name='服务器类型'),
        ),
    ]
