# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-20 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipdata', '0003_ipinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alldata',
            name='diskrate',
            field=models.CharField(max_length=10, verbose_name='硬盘使用率'),
        ),
        migrations.AlterField(
            model_name='alldata',
            name='memoryrate',
            field=models.CharField(max_length=10, verbose_name='内存使用率'),
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='diskrate',
            field=models.CharField(max_length=10, verbose_name='硬盘使用率'),
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='disktotal',
            field=models.DecimalField(decimal_places=1, max_digits=18, verbose_name='磁盘总量'),
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='diskuse',
            field=models.DecimalField(decimal_places=1, max_digits=18, verbose_name='磁盘使用量'),
        ),
        migrations.AlterField(
            model_name='ipinfo',
            name='memoryrate',
            field=models.CharField(max_length=18, verbose_name='内存使用率'),
        ),
    ]
